const images = {
  landingPage: require("./nigeria-flag.jpg"),
  mission: require("./mission.png"),
  company: require("./company.png"),
  volunteer: require("./volunteer.png"),
  project: require("./project.png"),
  about: require("./about.png"),
  vote: require("./vote.png"),
  voteMark: require("./votemark.png"),
  testimonial: require("./testimonial.png"),
  test1: require("./test1.png"),
  test2: require("./test2.png"),
  test3: require("./test3.png"),
  test4: require("./test4.png"),
  democracy: require("./democracy.jpeg"),
  service: require("./service.jpeg"),
  reward: require("./reward.jpeg"),
  recognition: require("./specialRecognition.jpeg"),
  legacy: require("./legacy.jpeg"),
  indira: require("./indira.jpg"),
  kennedy: require("./kennedy.jpg"),
  pierre: require("./pierre.jpg"),
  rufus: require("./rufus.jpg"),
  woodrow: require("./woodrow.jpg"),
  news2: require("./news2.jpeg"),
};

export default images;
